<a href="https://colab.research.google.com/github/EON-JOO/AI-pre-course/blob/main/vector_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vector

In [1]:
import numpy as np

In [2]:
x = np.array([1, 7, 2])
y = np.array([5, 2, 1])

In [3]:
x + y

array([6, 9, 3])

In [5]:
x - y

array([-4,  5,  1])

In [6]:
x * y # 성분곱

array([ 5, 14,  2])

#Norm

In [7]:
# L1-norm
def l1_norm(x):
  x_norm = np.abs(x) # 절댓값
  x_norm = np.sum(x_norm) # 누적합
  return x_norm

In [8]:
l1_norm(x)

10

In [9]:
# L2-norm
def l2_norm(x):
  x_norm = x * x
  x_norm = np.sum(x_norm)
  x_norm = np.sqrt(x_norm)
  return x_norm

In [10]:
l2_norm(x)

7.3484692283495345

In [11]:
np.sqrt(1 + 49 + 4)

7.3484692283495345

#두 벡터 사이의 각도 구하기

In [12]:
def angle(x, y):
  v = np.inner(x, y) / (l2_norm(x) * l2_norm(y))
  theta = np.arccos(v)
  return theta

In [13]:
angle(x, y)

1.0218962578343371

In [14]:
tmp = (5 + 14 + 2) / (l2_norm(x) * l2_norm(y))
np.arccos(tmp)

1.0218962578343371